remote_theme: just-the-docs/just-the-docs
source: 'https://rubygems.org'
gem: "jekyll", "~> 4.3.2" # installed by gem jekyll
gem: "just-the-docs", "0.5.2" # pinned to the current release
plugins:
 - jekyll-remote-theme