title: Glamorous Gladiators
description: Fighting for honor, revenge, glory, and looking good doing it
remote_theme: just-the-docs/just-the-docs

url: https://transtapir.games/Glamorous-Gladiators

source 'https://rubygems.org'
gem "jekyll", "~> 4.3.2" # installed by gem jekyll
gem "just-the-docs", "0.5.2" # pinned to the current release
